# 变量
variables:
  NODE_MODULES: $CI_PROJECT_DIR/node_modules
  DOCKER_REGISTRY: registry.us-west-1.aliyuncs.com/influx-global
  DOCKER_IMAGE_NAME: chatgpt-next-web
  DOCKER_IMAGE_TAG: $CI_COMMIT_TAG
  DOCKER_IMAGE: $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG

cache:
  key:
    files:
      - yarn.lock
  paths:
    - ${NODE_MODULES}

# 阶段
stages:
  - build

# 上传转换后的 surge 和 clash
build-image:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG != null
  tags:
    - hk
  before_script:
    - bun install
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE


